#!/bin/bash
set -euo pipefail

# Boom Warehouse — Cloudflare R2 Image Offloading Setup

echo "=== Boom Warehouse: Cloudflare R2 Setup ==="

# Install WP Offload Media Lite
echo "Installing WP Offload Media Lite..."
wp plugin install amazon-s3-and-cloudfront --activate

echo ""
echo "CLOUDFLARE R2 SETUP:"
echo ""
echo "1. CREATE R2 BUCKET:"
echo "   - Cloudflare Dashboard > R2 > Create Bucket"
echo "   - Bucket name: boom-warehouse-media"
echo "   - Location: Auto (or US East)"
echo ""
echo "2. CREATE R2 API TOKEN:"
echo "   - Cloudflare Dashboard > R2 > Manage R2 API Tokens"
echo "   - Create token with Object Read & Write permissions"
echo "   - Save Access Key ID and Secret Access Key"
echo ""
echo "3. CONFIGURE WP OFFLOAD MEDIA:"
echo "   - WP Admin > Settings > Offload Media"
echo "   - Storage Provider: Amazon S3 (R2 is S3-compatible)"
echo "   - Access Key ID: (from step 2)"
echo "   - Secret Access Key: (from step 2)"
echo "   - Custom Endpoint: https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
echo "   - Bucket: boom-warehouse-media"
echo "   - Path: wp-content/uploads/"
echo ""
echo "4. CUSTOM DOMAIN (for CDN):"
echo "   - R2 > boom-warehouse-media > Settings > Custom Domains"
echo "   - Add: media.boomwarehouse.com"
echo "   - Or use Cloudflare Workers for the cdn.boomwarehouse.com subdomain"
echo ""
echo "5. MIGRATE EXISTING MEDIA:"
echo "   - WP Offload Media > Tools > Copy Existing Media to R2"
echo "   - This will upload all existing images to R2"
echo "   - URLs automatically rewrite to serve from R2/CDN"
echo ""
echo "COST ESTIMATE:"
echo "  R2 pricing (very generous free tier):"
echo "  - Storage: 10 GB/month free, then \$0.015/GB"
echo "  - Class A ops (write): 1M/month free"
echo "  - Class B ops (read): 10M/month free"
echo "  - Egress: FREE (no bandwidth charges!)"
echo ""
echo "  For a store with ~500 products at ~5 images each:"
echo "  ~2,500 images × ~200KB avg = ~500MB → well within free tier"
echo ""
echo "=== R2 setup guide complete ==="
