#!/bin/bash
set -euo pipefail

# Boom Warehouse — Acima WooCommerce Plugin Configuration
# The official Acima plugin may require manual installation from their merchant portal.

echo "=== Boom Warehouse: Acima Lease-to-Own Configuration ==="

echo ""
echo "ACIMA PLUGIN INSTALLATION:"
echo ""
echo "1. Contact Acima (https://www.acima.com/merchants) to get merchant credentials"
echo "2. Download the official WooCommerce plugin from the Acima merchant portal"
echo "3. Upload via WP Admin > Plugins > Add New > Upload Plugin"
echo "4. Activate the plugin"
echo ""
echo "CONFIGURATION STEPS (WP Admin > WooCommerce > Settings > Payments > Acima):"
echo ""
echo "  - Enable: Yes"
echo "  - Merchant ID: (from Acima merchant portal)"
echo "  - API Key: (from Acima merchant portal)"
echo "  - Environment: Sandbox (for testing) / Production (for live)"
echo "  - Min Order Amount: \$50"
echo "  - Max Order Amount: \$5,000"
echo "  - Display on product pages: Yes"
echo "  - Display monthly estimate: Yes"
echo ""
echo "TESTING THE ACIMA FLOW:"
echo ""
echo "1. Ensure Acima plugin is in Sandbox mode"
echo "2. Add a product (\$50-\$5,000) to cart"
echo "3. Proceed to checkout"
echo "4. Select 'Acima Lease-to-Own' as payment method"
echo "5. Customer fills out Acima application (SSN, DOB, income)"
echo "6. Acima returns instant approval/denial"
echo "7. If approved: order is placed, Acima handles lease payments"
echo ""
echo "PRODUCTION SWITCH:"
echo "1. WP Admin > WooCommerce > Settings > Payments > Acima"
echo "2. Change Environment from 'Sandbox' to 'Production'"
echo "3. Enter production Merchant ID and API Key"
echo "4. Test with a small real order to verify"
echo ""
echo "NOTE: The Boom Warehouse theme already displays 'As low as \$X/mo with Acima'"
echo "on every product page where price is between \$50-\$5,000. This works independently"
echo "of the Acima plugin — it's a CTA that links to Acima's pre-qualification page."
